name: dart_pusher_channels
description: Dart implementation of client of Pusher Channels protocol, instrument to work with real-time applications. 
version: 1.2.3

environment:
  sdk: ">=3.4.0 <4.0.0"

repository: https://github.com/kerimamansaryyev/dart_pusher_channels

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

dependencies:
  http: ^0.13.5
  meta: ^1.8.0
  pinenacl: ^0.6.0
  rxdart: ^0.28.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  dart_code_metrics: ^5.7.6 
  lints: ^2.0.1
  test: ^1.25.8 
